
windowrule {
  name = noscreenshare
  match:class = obsidian|Element|io.github.tdesktop_x64.TDesktop|vmware|zen|vesktop
#  no_screen_share = on
}

#layerrule = no_screen_share on, match:namespace swaync-control-center
#layerrule = no_screen_share on, match:namespace swaync-notification-window