d                 seek   5
a                 seek  -5
RIGHT             seek   5
LEFT              seek  -5
Ctrl+d            seek  15
Ctrl+a            seek -15
Ctrl+RIGHT        seek  15
Ctrl+LEFT         seek -15
Shift+d           seek  60
Shift+a           seek -60
Shift+RIGHT       seek  60
Shift+LEFT        seek -60
WHEEL_UP          add volume  5
WHEEL_DOWN        add volume -5
Shift+WHEEL_UP    add volume  20
Shift+WHEEL_DOWN  add volume -20   
Alt+d             add video-rotate 90
Alt+a             add video-rotate -90
Alt+RIGHT         add video-rotate 90
Alt+LEFT          add video-rotate -90
Ctrl+=            add video-zoom 0.25
Ctrl+-            add video-zoom -0.25
Ctrl+WHEEL_UP     add video-zoom 0.25
Ctrl+WHEEL_DOWN   add video-zoom -0.25
Alt+WHEEL_UP      script-binding positioning/cursor-centric-zoom 0.1
Alt+WHEEL_DOWN    script-binding positioning/cursor-centric-zoom -0.1
Ctrl+MBTN_MID     set video-zoom 0; no-osd set panscan 0; no-osd set video-pan-x 0; no-osd set video-pan-y 0; no-osd set video-align-x 0; no-osd set video-align-y 0
Shift+WHEEL_UP    add speed 0.05
Shift+WHEEL_DOWN  add speed -0.05