keep-open=yes
save-position-on-quit=yes
autofit=60%
keepaspect=yes
scalewindowed=1.0
scalefullscreen=1.0
alpha=blend
force-window=padding=no
video-aspect-override=no

#osc=no
border=no

cache=yes
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=100MiB


hwdec=auto-safe
vo=gpu-next
gpu-api=auto
gpu-context=auto

video-sync=display-resample
profile=high-quality
interpolation=yes
tscale=oversample
cscale=ewa_lanczos
dscale=mitchell
dither-depth=auto

volume=70
volume-max=120

sub-font="Arial"
osd-font="sans-serif"
sub-auto=fuzzy

[extension.gif]
loop-file=yes
save-position-on-quit=no

[extension.mp3]
profile=audio-visualizer
save-position-on-quit=no

[extension.ogg]
profile=audio-visualizer
save-position-on-quit=no

[extension.wav]
profile=audio-visualizer
save-position-on-quit=no

[extension.flac]
profile=audio-visualizer
save-position-on-quit=no

[extension.m4a]
profile=audio-visualizer
save-position-on-quit=no

[audio-only]
keepaspect=no
profile-cond=vid==0 or not vid
lavfi-complex=[aid1]asplit[ao][v_audio];[v_audio]showfreqs=size=1120x720:mode=bar:cmode=combined:ascale=log:win_size=64:colors=white,lutrgb=r='if(eq(val,0),8,255)':g='if(eq(val,0),8,255)':b='if(eq(val,0),8,255)',drawgrid=w=35:h=720:t=12:c=0x080808,pad=1160:720:20:0:color=0x080808,format=yuv420p[vo]
wayland-app-id="mpv_only_audio_mpv"